// Mirror note: RESULT.md is the monorepo's build log for this server and is not
// published to a mirror, so it is dropped from the required-file list below. Every
// other file in that list is still checked.
// Mirror note: tests that need a signed Pro key are skipped here. The signing key
// lives only in the monorepo (keys/license-private.pem); run them there.
// Mirror note: tests that run a script from the monorepo's scripts/ directory are
// skipped here. That directory is not part of a server folder; run them in the monorepo.
// Contract suite for work-order. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/work-order/SPEC.md that a test can check without
// judgement: one version number across package.json, src/version.ts, serverInfo and all
// four registry manifests; the remotes rule (the mcpb manifest carries remotes.json, the
// stdio-only names carry none); JSON-RPC-only stdout; tool-description hygiene; the
// free/Pro tier switch; that nothing outside this server's own directory is written; and
// that the invoice engine is imported rather than restated. It never asserts a number a
// human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  client, sandbox, cleanup, proKey, storeDir, writeProfile, writeInvoiceClient, REPO, ORDER, LINES,
} from "./_client.mjs";

const HERE = REPO;
const PRODUCT = "work-order";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. Both lists are
 * defects; the fix is in src, not here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  writeProfile(box.dataHome);
  writeInvoiceClient(box.dataHome);
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test.skip("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-work-order");
  assert.match(pkg.version, /^\d+\.\d+\.\d+$/, "package version must be a plain semver; the release bump moves it, the test does not pin it");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-work-order");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.service-report.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until the release job hashes the bundle; after that, a real sha256.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/work-order)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/work-order");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.service-report.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/work-order",
    "io.github.theluckystrike/job-card",
    "io.github.theluckystrike/service-report",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { c } = open(t);
  await c.init();
  await c.tools();
  await c.call("work_order_create", ORDER);
  await c.call("work_order_get", { work_order: "WO-1999-0001" });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 12, "tool count changed; update servers/work-order/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "completion_report_pdf", "completion_report_text", "license_activate", "license_status",
    "work_order_add_line", "work_order_create", "work_order_delete", "work_order_get",
    "work_order_invoice_payload", "work_order_list", "work_order_status", "work_orders_report",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/[—]/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("the one tool that takes a file path says so imperatively, and no other tool takes one", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), ["completion_report_pdf"]);
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  assert.deepEqual(offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n)), []);
});

test.skip("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("the free tier is the documented one: the board and the text report are free, the rest is Pro", async (t) => {
  const { c } = open(t);
  await c.init();
  const id = (await c.json("work_order_create", ORDER)).created.id;
  for (const [tool, args] of [
    ["work_order_add_line", { work_order: id, ...LINES[0] }],
    ["work_order_status", { work_order: id, status: "scheduled", date: "2026-03-03" }],
    ["work_order_get", { work_order: id }],
    ["work_order_list", {}],
    ["completion_report_text", { work_order: id }],
  ]) {
    assert.equal((await c.call(tool, args)).isError, false, `${tool} was gated`);
  }
  for (const [tool, args] of [
    ["completion_report_pdf", { work_order: id }],
    ["work_order_invoice_payload", { work_order: id }],
    ["work_orders_report", {}],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, true, `${tool} answered on the free tier`);
    assert.match(r.text, /Pro is a one-time \$\d+ for this server/, tool);
    assert.match(r.text, /license_activate/, tool);
    // The conversion instrument: every gate link carries the tool that tripped it.
    assert.match(r.text, new RegExp(`src=${PRODUCT}\\.${tool}`), `${tool} gate link is untagged`);
  }
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { c } = open(t);
  await c.init();
  const res = (await c.send("resources/read", { uri: "workorder://board" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.statuses, ["draft", "scheduled", "in_progress", "done", "invoiced"]);
  assert.deepEqual(body.open_statuses, ["draft", "scheduled", "in_progress"]);
  assert.equal(body.free_tier.open_work_orders, 5);
  assert.deepEqual(body.free_tier.pro_tools.sort(),
    ["completion_report_pdf", "work_order_invoice_payload", "work_orders_report"]);
  assert.equal(body.creates_invoices, false);
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "work-order");
  assert.deepEqual(body.reads.map((r) => [r.store, r.writes]), [["invoice", false]]);
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["close_the_job"]);
});

test.skip("this server writes its own directory and no sibling store, on any tool", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const id = (await c.json("work_order_create", ORDER)).created.id;
  for (const l of LINES) await c.call("work_order_add_line", { work_order: id, ...l });
  await c.call("work_order_status", { work_order: id, status: "scheduled", date: "2026-03-03" });
  await c.call("work_order_status", { work_order: id, status: "in_progress", date: "2026-03-04" });
  await c.call("work_order_status", { work_order: id, status: "done", date: "2026-03-04" });
  await c.call("completion_report_text", { work_order: id });
  await c.call("completion_report_pdf", { work_order: id });
  await c.call("work_order_invoice_payload", { work_order: id });
  await c.call("work_orders_report", {});
  const second = (await c.json("work_order_create", { ...ORDER, description: "A second job" })).created.id;
  await c.call("work_order_delete", { work_order: second });

  const files = readdirSync(storeDir(box.dataHome)).filter((f) => !f.startsWith("."));
  assert.deepEqual(files.sort(), ["counter.json", "orders.json", "pdf"]);
  // The invoice store was READ and must be untouched: one file, the one the test wrote.
  const siblings = readdirSync(join(box.dataHome, "mcp-servers")).sort();
  assert.deepEqual(siblings, ["invoice", "profile", "work-order"], `a sibling store was created: ${siblings.join(", ")}`);
  assert.deepEqual(readdirSync(join(box.dataHome, "mcp-servers", "invoice")), ["clients.json"],
    "this server wrote into the invoice data directory; it must only read clients.json");
});

test.skip("no total is stored: an order record holds its lines and its history and nothing derived", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  await c.init();
  const id = (await c.json("work_order_create", { ...ORDER, note: "gate code 4471" })).created.id;
  for (const l of LINES) await c.call("work_order_add_line", { work_order: id, ...l });
  await c.call("work_order_status", { work_order: id, status: "scheduled", date: "2026-03-03" });
  const raw = readFileSync(join(storeDir(box.dataHome), "orders.json"), "utf8");
  // A derived figure stored under any of these keys is a second copy of what the lines say.
  // "vat_id" on the client record is an identity field, not a total, so the keys are exact.
  for (const key of ["total_minor", "net_minor", "gross_minor", "vat_minor", "labour_minor",
    "materials_minor", "value_minor", "hours_total", "billed_unit_minor"]) {
    assert.equal(raw.includes(`"${key}"`), false, `${key} was stored; every total must be derived on the call`);
  }
  const stored = JSON.parse(raw)[0];
  assert.deepEqual(Object.keys(stored).sort(), [
    "client", "client_id", "client_source", "created", "currency", "description", "history",
    "id", "lines", "note", "priority", "requested_date", "site_address", "status", "updated",
  ]);
  assert.deepEqual(Object.keys(stored.lines[0]).sort(),
    ["created", "date", "description", "hours", "id", "kind", "rate_minor", "rate_source"]);
  assert.deepEqual(Object.keys(stored.lines[2]).sort(),
    ["created", "date", "description", "id", "kind", "markup_percent", "quantity", "unit_cost_minor"]);
});

test("the money engine is the invoice server's own, not a copy", async () => {
  // If servers/invoice changes its rounding basis, this server must change with it, which
  // it does because it never implements the arithmetic: it imports it.
  const order = readFileSync(join(HERE, "src", "order.ts"), "utf8");
  assert.match(order, /import \{[^}]*computeTotals[^}]*\} from "@theluckystrike\/mcp-invoice\/lib";/,
    "the totals must come from the invoice server, never be restated here");
  assert.match(order, /roundHalfUp/, "the rounding must be the invoice server's roundHalfUp");
  for (const forbidden of [/function roundHalfUp/, /function computeTotals/, /Math\.round\(/]) {
    assert.equal(forbidden.test(order), false, `src/order.ts reimplements ${forbidden}`);
  }
  const index = readFileSync(join(HERE, "src", "index.ts"), "utf8");
  assert.match(index, /import \{ renderDocPdf \} from "@theluckystrike\/mcp-billing-docs\/lib";/,
    "the A4 renderer must be imported from billing-docs, never reproduced here");
  assert.match(index, /findClient/, "client records must come from the invoice store");
});

test("src holds no network call and no stdout write", async () => {
  // grep exits 1 on no match, which is the passing case here.
  let raw = "";
  try {
    raw = execFileSync("grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const out = raw.trim().split("\n").filter(Boolean);
  const offending = out.filter((l) => !/mcp\.zovo\.one|github\.com|modelcontextprotocol\.io/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});

test("the required files are all present", () => {
  for (const f of [
    "package.json", "tsconfig.json", "README.md", "LICENSE", "SPEC.md",
    "server.json", "server.mcpb.json", "server.variant.json", "server.service-report.json",
    "remotes.json", "smithery.yaml", "glama.json", "llms-install.md", "Dockerfile",
    "src/index.ts", "src/lib.ts", "src/order.ts", "src/store.ts", "src/version.ts",
  ]) {
    assert.ok(existsSync(join(HERE, f)), `missing ${f}`);
  }
});

test.skip("every amount the server emits is an integer number of minor units", async (t) => {
  const { c } = open(t, { key: proKey() });
  await c.init();
  const created = await c.json("work_order_create", ORDER);
  for (const k of ["net_minor", "labour_minor", "materials_minor"]) assert.ok(Number.isInteger(created.created[k]), k);
  const id = created.created.id;
  for (const l of LINES) await c.call("work_order_add_line", { work_order: id, ...l });
  const got = (await c.json("work_order_get", { work_order: id })).work_order;
  for (const k of ["net_minor", "labour_minor", "materials_minor", "parts_cost_minor", "markup_earned_minor", "vat_minor", "gross_minor"]) {
    assert.ok(Number.isInteger(got[k]), `${k} is not an integer: ${got[k]}`);
  }
  for (const l of got.lines_detail) {
    assert.ok(Number.isInteger(l.value_minor), JSON.stringify(l));
    if (l.kind === "parts") assert.ok(Number.isInteger(l.billed_unit_minor) && Number.isInteger(l.unit_cost_minor));
    else assert.ok(Number.isInteger(l.rate_minor));
  }
  const p = await c.json("work_order_invoice_payload", { work_order: id });
  for (const k of ["subtotal_minor", "net_minor", "vat_minor", "total_minor"]) {
    assert.ok(Number.isInteger(p.totals[k]), `${k} is not an integer: ${p.totals[k]}`);
  }
  assert.equal(p.totals.net_minor + p.totals.vat_minor, p.totals.total_minor, "net plus VAT does not make the total");
});
